services:
  mysql:
    image: mysql:8.4.3
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database      
    ports: 
    - "3306:3306" 
